######################################################################
# Automatically generated by qmake (2.01a) Fr. Nov 8 17:11:49 2013
######################################################################

TEMPLATE = app
TARGET = OpenOCD-QtGUI
DEPENDPATH += . QtTelnet
INCLUDEPATH += . QtTelnet

QT += network widgets
HEADERS += mainwidget.h QtTelnet/qttelnet.h
FORMS += mainwidget.ui
SOURCES += main.cpp mainwidget.cpp QtTelnet/qttelnet.cpp
